models/Ticket.php
<?php

namespace app\models;

use Yii;
use \app\models\base\Ticket as BaseTicket;

/**
 * This is the model class for table "ticket".
 */
class Ticket extends BaseTicket
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return array_replace_recursive(parent::rules(),
	    [
            [['subject', 'detail', 'model_id', 'model_manufacture_id', 'contact_id', 'contact_Customer_id'], 'required'],
            [['subject', 'detail'], 'string'],
            [['issue_date', 'created_at', 'updated_at'], 'safe'],
            [['created_by', 'updated_by', 'status', 'model_id', 'model_manufacture_id'], 'integer'],
            [['id', 'contact_id', 'contact_Customer_id'], 'string', 'max' => 255],
            [['technitian'], 'string', 'max' => 50]
        ]);
    }
	
}

controllers/ContactController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Contact;
use app\models\Contactemail;
use app\models\Contactphone;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;

/**
 * ContactController implements the CRUD actions for Contact model.
 */
class ContactController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index', 'view', 'create', 'update','delete',
                            'pdf', 'add-contactemail', 'add-contactphone'], //'add-ticket' could be integrated next version
                        'roles' => ['@']
                    ],
                    [
                        'allow' => false
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Contact models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Contact::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Contact model.
     * @param string $id
     * @param string $customer_id
     * @return mixed
     */
    public function actionView($id, $customer_id)
    {
        $model = $this->findModel($id, $customer_id);
        $providerContactemail = new \yii\data\ArrayDataProvider([
            'allModels' => $model->contactemails,
        ]);
        $providerContactphone = new \yii\data\ArrayDataProvider([
            'allModels' => $model->contactphones,
        ]);
        $providerTicket = new \yii\data\ArrayDataProvider([
            'allModels' => $model->tickets,
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id, $customer_id),
            'providerContactemail' => $providerContactemail,
            'providerContactphone' => $providerContactphone,
            'providerTicket' => $providerTicket,
        ]);
    }

    /**
     * Creates a new Contact model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Contact();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            Yii::$app->session->setFlash('success', [
                'type' => 'success',
                'icon' => 'fa fa-user',
                'message' => Html::encode('Thanks for submit your Customer Contact. We are working on it'),
                'title' => Html::encode('Customer Contact Created'),
            ]); //Notify to the View
            return $this->redirect(['view', 'id' => $model->id, 'customer_id' => $model->customer_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Contact model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @param string $customer_id
     * @return mixed
     */
    public function actionUpdate($id, $customer_id)
    {
        $model = $this->findModel($id, $customer_id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            Yii::$app->session->setFlash('success', [
                'type' => 'success',
                'icon' => 'fa fa-user',
                'message' => Html::encode('Thanks for update this Customer Contact.'),
                'title' => Html::encode('Customer Contact Updated'),
            ]); //Notify to the View
            return $this->redirect(['view', 'id' => $model->id, 'customer_id' => $model->customer_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Contact model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @param string $customer_id
     * @return mixed
     */
    public function actionDelete($id, $customer_id)
    {
        $this->findModel($id, $customer_id)->delete(); //Check deleteWithRelation

        return $this->redirect(['index']);
    }
    
    /**
     * 
     * for export pdf at actionView
     *  
     * @param type $id
     * @return type
     */
    public function actionPdf($id) {
        $model = $this->findModel($id);
        $providerContactemail = new \yii\data\ArrayDataProvider([
            'allModels' => $model->contactemails,
        ]);
        $providerContactphone = new \yii\data\ArrayDataProvider([
            'allModels' => $model->contactphones,
        ]);
        $providerTicket = new \yii\data\ArrayDataProvider([
            'allModels' => $model->tickets,
        ]);

        $content = $this->renderAjax('_pdf', [
            'model' => $model,
            'providerContactemail' => $providerContactemail,
            'providerContactphone' => $providerContactphone,
            'providerTicket' => $providerTicket,
        ]);

        $pdf = new \kartik\mpdf\Pdf([
            'mode' => \kartik\mpdf\Pdf::MODE_CORE,
            'format' => \kartik\mpdf\Pdf::FORMAT_A4,
            'orientation' => \kartik\mpdf\Pdf::ORIENT_PORTRAIT,
            'destination' => \kartik\mpdf\Pdf::DEST_BROWSER,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => \Yii::$app->name],
            'methods' => [
                'SetHeader' => [\Yii::$app->name],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);

        return $pdf->render();
    }
    
    /**
     * Finds the Contact model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @param string $customer_id
     * @return Contact the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $customer_id)
    {
        if (($model = Contact::findOne(['id' => $id, 'customer_id' => $customer_id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Action to load a tabular form grid for Contact email
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionAddContactemail()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('Contactemail');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('action') == 'load' && empty($row)) || Yii::$app->request->post('action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formContactemail', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Action to load a tabular form grid for Contact Phone
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionAddContactphone()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('Contactphone');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('action') == 'load' && empty($row)) || Yii::$app->request->post('action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formContactphone', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Action to load a tabular form grid for Ticket
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionAddTicket()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('Ticket');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('action') == 'load' && empty($row)) || Yii::$app->request->post('action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formTicket', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/ModelController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Model;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\Html;

/**
 * ModelController implements the CRUD actions for Model model.
 */
class ModelController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => [
                            'index', 'view', 'create', 'update','delete',
                            'pdf', //'add-ticket', when the _formTicket was done.
                        ],
                        'roles' => ['@']
                    ],
                    [
                        'allow' => false
                    ]
                ]
            ]
        ];
    }

    /**
     * Lists all Model models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Model::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Model model.
     * @param integer $id
     * @param integer $manufacture_id
     * @return mixed
     */
    public function actionView($id, $manufacture_id)
    {
        $model = $this->findModel($id, $manufacture_id);
        $providerTicket = new \yii\data\ArrayDataProvider([
            'allModels' => $model->tickets,
        ]);
        return $this->render('view', [
            'model' => $this->findModel($id, $manufacture_id),
            'providerTicket' => $providerTicket,
        ]);
    }

    /**
     * Creates a new Model model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Model();

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            Yii::$app->session->setFlash('success', [
                'type' => 'success',
                'icon' => 'fa fa-cube',
                'message' => Html::encode('Thanks for submit the Equipment Model. Great Creation.'),
                'title' => Html::encode('Equipment Model Created'),
            ]); //Notify to the View
            return $this->redirect(['view', 'id' => $model->id, 'manufacture_id' => $model->manufacture_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Model model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @param integer $manufacture_id
     * @return mixed
     */
    public function actionUpdate($id, $manufacture_id)
    {
        $model = $this->findModel($id, $manufacture_id);

        if ($model->loadAll(Yii::$app->request->post()) && $model->saveAll()) {
            Yii::$app->session->setFlash('success', [
                'type' => 'success',
                'icon' => 'fa fa-cube',
                'message' => Html::encode('Thanks for update this Equipment Model.'),
                'title' => Html::encode('Equipment Model Updated'),
            ]); //Notify to the View
            return $this->redirect(['view', 'id' => $model->id, 'manufacture_id' => $model->manufacture_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Model model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @param integer $manufacture_id
     * @return mixed
     */
    public function actionDelete($id, $manufacture_id)
    {
        $this->findModel($id, $manufacture_id)->deleteWithRelated();

        return $this->redirect(['index']);
    }
    
    /**
     * 
     * for export pdf at actionView
     *  
     * @param type $id
     * @return type
     */
    public function actionPdf($id) {
        $model = $this->findModel($id);
        $providerTicket = new \yii\data\ArrayDataProvider([
            'allModels' => $model->tickets,
        ]);

        $content = $this->renderAjax('_pdf', [
            'model' => $model,
            'providerTicket' => $providerTicket,
        ]);

        $pdf = new \kartik\mpdf\Pdf([
            'mode' => \kartik\mpdf\Pdf::MODE_CORE,
            'format' => \kartik\mpdf\Pdf::FORMAT_A4,
            'orientation' => \kartik\mpdf\Pdf::ORIENT_PORTRAIT,
            'destination' => \kartik\mpdf\Pdf::DEST_BROWSER,
            'content' => $content,
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            'cssInline' => '.kv-heading-1{font-size:18px}',
            'options' => ['title' => \Yii::$app->name],
            'methods' => [
                'SetHeader' => [\Yii::$app->name],
                'SetFooter' => ['{PAGENO}'],
            ]
        ]);

        return $pdf->render();
    }
    
    /**
     * Finds the Model model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @param integer $manufacture_id
     * @return Model the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id, $manufacture_id)
    {
        if (($model = Model::findOne(['id' => $id, 'manufacture_id' => $manufacture_id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Action to load a tabular form grid for Ticket
     * @return mixed
     * @throws NotFoundHttpException
     */
    public function actionAddTicket()
    {
        if (Yii::$app->request->isAjax) {
            $row = Yii::$app->request->post('Ticket');
            if((Yii::$app->request->post('isNewRecord') && Yii::$app->request->post('action') == 'load' && empty($row)) || Yii::$app->request->post('action') == 'add')
                $row[] = [];
            return $this->renderAjax('_formTicket', ['row' => $row]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/ticket/_detail.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;
use kartik\icons\Icon;

Icon::map($this); //Load default Font Awesome Icon Set

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

?>
<div class="ticket-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= Html::encode($model->subject) ?></h2>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'hidden' => true],
        'subject:ntext',
        'detail:ntext',
        'technitian',
        'issue_date',
        [
            'attribute' => 'model.manufacture.name',
            'label' => 'Manufacture',
        ],
        [
            'attribute' => 'model.name',
            'label' => 'Model',
        ],
        [
            'attribute' => 'contact.customer.name',
            'label' => 'Customer',
        ],
        [
            'attribute' => 'contact.fullname',
            'label' => 'Contact',
        ],
        'status',
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>

views/ticket/_expand.php
<?php
use yii\helpers\Html;
use kartik\tabs\TabsX;
use yii\helpers\Url;
use kartik\icons\Icon;

Icon::map($this); //Load default Font Awesome Icon Set
$items = [
    [
        'label' => Icon::show('ticket'). Html::encode('Ticket'),
        'content' => $this->render('_detail', [
            'model' => $model,
        ]),
    ],
        ];
echo TabsX::widget([
    'items' => $items,
    'position' => TabsX::POS_ABOVE,
    'encodeLabels' => false,
    'class' => 'tes',
    'pluginOptions' => [
        'bordered' => true,
        'sideways' => true,
        'enableCache' => false
        //        'height' => TabsX::SIZE_TINY
    ],
    'pluginEvents' => [
        "tabsX.click" => "function(e) {setTimeout(function(e){
                if ($('.nav-tabs > .active').next('li').length == 0) {
                    $('#prev').show();
                    $('#next').hide();
                } else if($('.nav-tabs > .active').prev('li').length == 0){
                    $('#next').show();
                    $('#prev').hide();
                }else{
                    $('#next').show();
                    $('#prev').show();
                };
                console.log(JSON.stringify($('.active', '.nav-tabs').html()));
            },10)}",
    ],
]);
?>

views/ticket/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\icons\Icon;

Icon::map($this); //Load default Font Awesome Icon Set

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="ticket-form">

    <?php $form = ActiveForm::begin(); ?>
    
    <?= $form->errorSummary($model); ?>

    <?= $form->field($model, 'id', ['template' => '{input}'])->textInput(['style' => 'display:none']); ?>

    <?= $form->field($model, 'subject')->textInput(['placeholder' => 'Problem Subject']) ?>

    <?= $form->field($model, 'detail')->textarea(['rows' => 6]) ?>

    <!-- Technitian Name & Issue Date -->
    <div class="row">
        <div class="form-group col-xs-12 col-sm-6">
            <?= $form->field($model, 'issue_date')->widget(\kartik\widgets\DateTimePicker::classname(), [
                'options' => ['placeholder' => 'Choose Issue Date'],
                'pluginOptions' => [
                    'autoclose' => true,
                    'format' => 'yyyy/mm/dd hh:ii:ss'
                ]
            ]) ?>
        </div>
        <div class="form-group col-xs-12 col-sm-6">
            <?= $form->field($model, 'technitian')->textInput(['maxlength' => true, 'placeholder' => 'Technitian']) ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-xs-12 col-sm-6">
            <!-- Manufacture Selection -->
            <?= $form->field($model, 'model_manufacture_id')->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\Manufacture::find()->orderBy('id')->asArray()->all(), 'id', 'name'), [
                'prompt' => 'Chose a manufacture',
                'id' => 'manufacture_id'
            ]); ?>
            <?= Html::a(Icon::show('plus') . 'Add Manufacture', ['/manufacture/create'], ['class' => 'btn btn-warning']); ?>
        </div>
        <div class="form-group col-xs-12 col-sm-6">
            <!-- Model Child of Manufacture -->
            <?= $form->field($model, 'model_id')->widget(\kartik\widgets\DepDrop::classname(), [
                'type'=>\kartik\widgets\DepDrop::TYPE_SELECT2,
                'select2Options'=>[
                    'pluginOptions'=>['allowClear'=>true]
                ],
                'pluginOptions'=>[
                    'depends'=>['manufacture_id'],
                    'placeholder'=>'Select equipment model',
                    'url'=>\yii\helpers\Url::to(['manufacturemodel']),
                    'initialize' => (!$model->isNewRecord),
                ]
            ]); ?>
            <?= Html::a(Icon::show('plus') . 'Add Model', ['/model/create'], ['class' => 'btn btn-warning']); ?>
        </div>
    </div>

    <div class="row">
        <div class="form-group col-xs-12 col-sm-6">
            <!-- Customer Selection -->
            <?= $form->field($model, 'contact_Customer_id')->dropDownList(\yii\helpers\ArrayHelper::map(\app\models\Customer::find()->orderBy('id')->asArray()->all(), 'id', 'name'), [
                'prompt' => 'Chose the Customer',
                'id' => 'customer_id'
            ]); ?>
        </div>
        <div class="form-group col-xs-12 col-sm-6">
            <!-- Contact Related to the Customer -->
            <?= $form->field($model, 'contact_id')->widget(\kartik\widgets\DepDrop::classname(), [
                'type'=>\kartik\widgets\DepDrop::TYPE_SELECT2,
                'select2Options'=>[
                    'pluginOptions'=>['allowClear'=>true],
                ],
                'pluginOptions'=>[
                    'depends'=>['customer_id'],
                    'placeholder'=>'Select the contact',
                    'url'=>\yii\helpers\Url::to(['customercontact']),
                    'initialize' => (!$model->isNewRecord),
                ]
            ]); ?>
            <?= Html::a(Icon::show('plus') . 'Add Contact', ['/contact/create'], ['class' => 'btn btn-warning']); ?>
        </div>
    </div>

    <!-- Right now this feature is not important for this level
    <?= $form->field($model, 'status')->textInput(['placeholder' => 'Status']) ?>
    -->

    <div class="form-group" id="add-manufacture"></div>

    <div class="form-group" id="add-model"></div>

    <div class="form-group" id="add-model"></div>
    <div class="form-group" id="add-model"></div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Cancel'),['index'],['class'=> 'btn btn-danger']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/ticket/_formModel.php
<?php
use kartik\grid\GridView;
use kartik\builder\TabularForm;
use yii\data\ArrayDataProvider;
use yii\helpers\Html;
use yii\widgets\Pjax;
use kartik\icons\Icon;

Icon::map($this); //Load default Font Awesome Icon Set

Pjax::begin();
$dataProvider = new ArrayDataProvider([
    'allModels' => $row,
    'pagination' => [
        'pageSize' => -1
    ]
]);
echo TabularForm::widget([
    'dataProvider' => $dataProvider,
    'formName' => 'Model',
    'checkboxColumn' => false,
    'actionColumn' => false,
    'attributeDefaults' => [
        'type' => TabularForm::INPUT_TEXT,
    ],
    'attributes' => [
        "id" => ['type' => TabularForm::INPUT_HIDDEN, 'columnOptions'=>['hidden'=>true]],
        'name' => ['type' => TabularForm::INPUT_TEXT],
        'del' => [
            'type' => 'raw',
            'label' => '',
            'value' => function($model, $key) {
                return Html::a('<i class="glyphicon glyphicon-trash"></i>', '#', ['title' =>  'Delete', 'onClick' => 'delRowModel(' . $key . '); return false;', 'id' => 'model-del-btn']);
            },
        ],
    ],
    'gridSettings' => [
        'panel' => [
            'heading' => Icon::show('cube') . 'Equipment Model List',
            'type' => GridView::TYPE_INFO,
            'before' => false,
            'footer' => false,
            'after' => Html::button('<i class="glyphicon glyphicon-plus"></i>' . 'Add Equipment Model', ['type' => 'button', 'class' => 'btn btn-success kv-batch-create', 'onClick' => 'addRowModel()']),
        ]
    ]
]);
Pjax::end();
?>

views/ticket/_pdf.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Ticket', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ticket-view">

    <div class="row">
        <div class="col-sm-9">
            <h2><?= 'Ticket'.' '. Html::encode($this->title) ?></h2>
        </div>
    </div>

    <div class="row">
<?php 
    $gridColumn = [
        ['attribute' => 'id', 'hidden' => true],
        'subject:ntext',
        'detail:ntext',
        'technitian',
        'issue_date',
        'status',
        [
            'attribute' => 'model.id',
            'label' => 'Model'
        ],
        'model_manufacture_id',
        [
            'attribute' => 'contact.id',
            'label' => 'Contact'
        ],
        'contact_Customer_id',
    ];
    echo DetailView::widget([
        'model' => $model,
        'attributes' => $gridColumn
    ]); 
?>
    </div>
</div>

views/ticket/_script.php
<?php
use yii\helpers\Url;

?>
<script>
    $(function () {
        var data = <?= $value ?>;
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: {'<?= $class?>' : data, action : 'load', isNewRecord : <?= $isNewRecord ?>},
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    });
    function addRow<?= $class ?>() {
        var data = $('#add-<?= $relID?> :input').serializeArray();
        data.push({name: 'action', value : 'add'});
        $.ajax({
            type: 'POST',
            url: '<?php echo Url::to(['add-'.$relID]); ?>',
            data: data,
            success: function (data) {
                $('#add-<?= $relID?>').html(data);
            }
        });
    }
    function delRow<?= $class ?>(id) {
        $('#add-<?= $relID?> tr[data-key=' + id + ']').remove();
    }
</script>

views/ticket/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Create Ticket';
$this->params['breadcrumbs'][] = ['label' => 'Ticket', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ticket-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/ticket/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Ticket */

$this->title = 'Update Ticket: ' . ' ' . $model->subject;
$this->params['breadcrumbs'][] = ['label' => 'Ticket', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->subject, 'url' => ['view', 'id' => $model->id, 'model_id' => $model->model_id, 'model_manufacture_id' => $model->model_manufacture_id, 'contact_id' => $model->contact_id, 'contact_Customer_id' => $model->contact_Customer_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ticket-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>